---
language: ruby
cache: bundler
sudo: false

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock

jobs:
  include:
    - stage: check
      rvm: 2.4.5
      script:
        - bundle exec rake pkg:compare_latest_tag
        - bundle exec rake pkg:create_tag_changelog

    - stage: deploy
      rvm: 2.4.5
      script:
        - true
      before_deploy:
        - "export SPECFILE_VERSION=`rpm -q --specfile build/*.spec --queryformat '%{VERSION}'`"
        - '[[ $TRAVIS_TAG =~ ^${SPECFILE_VERSION}$ ]]'
      deploy:
        - provider: releases
          api_key:
            secure: TBD
          skip_cleanup: true
          on:
            tags: true
            condition: '($SKIP_FORGE_PUBLISH != true)'
